version: '3'
services:
#  app:
#    container_name: 'next'
#    build: .
#    restart: always
#    ports:
#      - "3006:3000"
#    volumes:
#      - ./app:/usr/src/app
  cms:
    image: agentejo/cockpit
    ports:
      - "8080:80"
    container_name: 'cms'
    volumes:
      - ./cockpit/storage:/var/www/html/storage/
